apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-nov13-2-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-nov13-2-test 
  name: py-nov13-2-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-nov13-2-test 
